//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controller.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultasSoap", Namespace="http://tempuri.org/")]
    public partial class Consultas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBonificacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBonificacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getColaboradoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCompaniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMontosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRecargasOperationCompleted;
        
        private System.Threading.SendOrPostCallback getColaboradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback setBonificacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback setColaboradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback setCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback setMontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRecargaOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateBonificacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateColaboradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteColaboradorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Consultas() {
            this.Url = global::Controller.Properties.Settings.Default.Controller_WebReference_Consultas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event getBonificacionesCompletedEventHandler getBonificacionesCompleted;
        
        /// <remarks/>
        public event getBonificacionCompletedEventHandler getBonificacionCompleted;
        
        /// <remarks/>
        public event getColaboradoresCompletedEventHandler getColaboradoresCompleted;
        
        /// <remarks/>
        public event getCompaniasCompletedEventHandler getCompaniasCompleted;
        
        /// <remarks/>
        public event getMontosCompletedEventHandler getMontosCompleted;
        
        /// <remarks/>
        public event getRecargasCompletedEventHandler getRecargasCompleted;
        
        /// <remarks/>
        public event getColaboradorCompletedEventHandler getColaboradorCompleted;
        
        /// <remarks/>
        public event setBonificacionCompletedEventHandler setBonificacionCompleted;
        
        /// <remarks/>
        public event setColaboradorCompletedEventHandler setColaboradorCompleted;
        
        /// <remarks/>
        public event setCompaniaCompletedEventHandler setCompaniaCompleted;
        
        /// <remarks/>
        public event setMontoCompletedEventHandler setMontoCompleted;
        
        /// <remarks/>
        public event setRecargaCompletedEventHandler setRecargaCompleted;
        
        /// <remarks/>
        public event updateBonificacionCompletedEventHandler updateBonificacionCompleted;
        
        /// <remarks/>
        public event updateColaboradorCompletedEventHandler updateColaboradorCompleted;
        
        /// <remarks/>
        public event deleteColaboradorCompletedEventHandler deleteColaboradorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string login(string usuario, string clave) {
            object[] results = this.Invoke("login", new object[] {
                        usuario,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string usuario, string clave) {
            this.loginAsync(usuario, clave, null);
        }
        
        /// <remarks/>
        public void loginAsync(string usuario, string clave, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        usuario,
                        clave}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBonificaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBonificaciones() {
            object[] results = this.Invoke("getBonificaciones", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBonificacionesAsync() {
            this.getBonificacionesAsync(null);
        }
        
        /// <remarks/>
        public void getBonificacionesAsync(object userState) {
            if ((this.getBonificacionesOperationCompleted == null)) {
                this.getBonificacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBonificacionesOperationCompleted);
            }
            this.InvokeAsync("getBonificaciones", new object[0], this.getBonificacionesOperationCompleted, userState);
        }
        
        private void OngetBonificacionesOperationCompleted(object arg) {
            if ((this.getBonificacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBonificacionesCompleted(this, new getBonificacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBonificacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBonificacion(int idCompania, int idMonto) {
            object[] results = this.Invoke("getBonificacion", new object[] {
                        idCompania,
                        idMonto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBonificacionAsync(int idCompania, int idMonto) {
            this.getBonificacionAsync(idCompania, idMonto, null);
        }
        
        /// <remarks/>
        public void getBonificacionAsync(int idCompania, int idMonto, object userState) {
            if ((this.getBonificacionOperationCompleted == null)) {
                this.getBonificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBonificacionOperationCompleted);
            }
            this.InvokeAsync("getBonificacion", new object[] {
                        idCompania,
                        idMonto}, this.getBonificacionOperationCompleted, userState);
        }
        
        private void OngetBonificacionOperationCompleted(object arg) {
            if ((this.getBonificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBonificacionCompleted(this, new getBonificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getColaboradores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getColaboradores() {
            object[] results = this.Invoke("getColaboradores", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getColaboradoresAsync() {
            this.getColaboradoresAsync(null);
        }
        
        /// <remarks/>
        public void getColaboradoresAsync(object userState) {
            if ((this.getColaboradoresOperationCompleted == null)) {
                this.getColaboradoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetColaboradoresOperationCompleted);
            }
            this.InvokeAsync("getColaboradores", new object[0], this.getColaboradoresOperationCompleted, userState);
        }
        
        private void OngetColaboradoresOperationCompleted(object arg) {
            if ((this.getColaboradoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getColaboradoresCompleted(this, new getColaboradoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCompanias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCompanias() {
            object[] results = this.Invoke("getCompanias", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCompaniasAsync() {
            this.getCompaniasAsync(null);
        }
        
        /// <remarks/>
        public void getCompaniasAsync(object userState) {
            if ((this.getCompaniasOperationCompleted == null)) {
                this.getCompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCompaniasOperationCompleted);
            }
            this.InvokeAsync("getCompanias", new object[0], this.getCompaniasOperationCompleted, userState);
        }
        
        private void OngetCompaniasOperationCompleted(object arg) {
            if ((this.getCompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompaniasCompleted(this, new getCompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMontos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getMontos() {
            object[] results = this.Invoke("getMontos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMontosAsync() {
            this.getMontosAsync(null);
        }
        
        /// <remarks/>
        public void getMontosAsync(object userState) {
            if ((this.getMontosOperationCompleted == null)) {
                this.getMontosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMontosOperationCompleted);
            }
            this.InvokeAsync("getMontos", new object[0], this.getMontosOperationCompleted, userState);
        }
        
        private void OngetMontosOperationCompleted(object arg) {
            if ((this.getMontosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMontosCompleted(this, new getMontosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRecargas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getRecargas(int idPersona) {
            object[] results = this.Invoke("getRecargas", new object[] {
                        idPersona});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getRecargasAsync(int idPersona) {
            this.getRecargasAsync(idPersona, null);
        }
        
        /// <remarks/>
        public void getRecargasAsync(int idPersona, object userState) {
            if ((this.getRecargasOperationCompleted == null)) {
                this.getRecargasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRecargasOperationCompleted);
            }
            this.InvokeAsync("getRecargas", new object[] {
                        idPersona}, this.getRecargasOperationCompleted, userState);
        }
        
        private void OngetRecargasOperationCompleted(object arg) {
            if ((this.getRecargasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRecargasCompleted(this, new getRecargasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getColaborador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getColaborador(int idPersona) {
            object[] results = this.Invoke("getColaborador", new object[] {
                        idPersona});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getColaboradorAsync(int idPersona) {
            this.getColaboradorAsync(idPersona, null);
        }
        
        /// <remarks/>
        public void getColaboradorAsync(int idPersona, object userState) {
            if ((this.getColaboradorOperationCompleted == null)) {
                this.getColaboradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetColaboradorOperationCompleted);
            }
            this.InvokeAsync("getColaborador", new object[] {
                        idPersona}, this.getColaboradorOperationCompleted, userState);
        }
        
        private void OngetColaboradorOperationCompleted(object arg) {
            if ((this.getColaboradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getColaboradorCompleted(this, new getColaboradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setBonificacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool setBonificacion(string bonificacion, int idMonto, int idCompania) {
            object[] results = this.Invoke("setBonificacion", new object[] {
                        bonificacion,
                        idMonto,
                        idCompania});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setBonificacionAsync(string bonificacion, int idMonto, int idCompania) {
            this.setBonificacionAsync(bonificacion, idMonto, idCompania, null);
        }
        
        /// <remarks/>
        public void setBonificacionAsync(string bonificacion, int idMonto, int idCompania, object userState) {
            if ((this.setBonificacionOperationCompleted == null)) {
                this.setBonificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetBonificacionOperationCompleted);
            }
            this.InvokeAsync("setBonificacion", new object[] {
                        bonificacion,
                        idMonto,
                        idCompania}, this.setBonificacionOperationCompleted, userState);
        }
        
        private void OnsetBonificacionOperationCompleted(object arg) {
            if ((this.setBonificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setBonificacionCompleted(this, new setBonificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setColaborador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool setColaborador(string nombre, string apepat, string apemat, string usuario, string clave, string saldo) {
            object[] results = this.Invoke("setColaborador", new object[] {
                        nombre,
                        apepat,
                        apemat,
                        usuario,
                        clave,
                        saldo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setColaboradorAsync(string nombre, string apepat, string apemat, string usuario, string clave, string saldo) {
            this.setColaboradorAsync(nombre, apepat, apemat, usuario, clave, saldo, null);
        }
        
        /// <remarks/>
        public void setColaboradorAsync(string nombre, string apepat, string apemat, string usuario, string clave, string saldo, object userState) {
            if ((this.setColaboradorOperationCompleted == null)) {
                this.setColaboradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetColaboradorOperationCompleted);
            }
            this.InvokeAsync("setColaborador", new object[] {
                        nombre,
                        apepat,
                        apemat,
                        usuario,
                        clave,
                        saldo}, this.setColaboradorOperationCompleted, userState);
        }
        
        private void OnsetColaboradorOperationCompleted(object arg) {
            if ((this.setColaboradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setColaboradorCompleted(this, new setColaboradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool setCompania(string compania) {
            object[] results = this.Invoke("setCompania", new object[] {
                        compania});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setCompaniaAsync(string compania) {
            this.setCompaniaAsync(compania, null);
        }
        
        /// <remarks/>
        public void setCompaniaAsync(string compania, object userState) {
            if ((this.setCompaniaOperationCompleted == null)) {
                this.setCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetCompaniaOperationCompleted);
            }
            this.InvokeAsync("setCompania", new object[] {
                        compania}, this.setCompaniaOperationCompleted, userState);
        }
        
        private void OnsetCompaniaOperationCompleted(object arg) {
            if ((this.setCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setCompaniaCompleted(this, new setCompaniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setMonto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool setMonto(string monto) {
            object[] results = this.Invoke("setMonto", new object[] {
                        monto});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setMontoAsync(string monto) {
            this.setMontoAsync(monto, null);
        }
        
        /// <remarks/>
        public void setMontoAsync(string monto, object userState) {
            if ((this.setMontoOperationCompleted == null)) {
                this.setMontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetMontoOperationCompleted);
            }
            this.InvokeAsync("setMonto", new object[] {
                        monto}, this.setMontoOperationCompleted, userState);
        }
        
        private void OnsetMontoOperationCompleted(object arg) {
            if ((this.setMontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setMontoCompleted(this, new setMontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setRecarga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool setRecarga(string numero, int idPersona, int idBonificacion, int idMonto, int idCompania) {
            object[] results = this.Invoke("setRecarga", new object[] {
                        numero,
                        idPersona,
                        idBonificacion,
                        idMonto,
                        idCompania});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setRecargaAsync(string numero, int idPersona, int idBonificacion, int idMonto, int idCompania) {
            this.setRecargaAsync(numero, idPersona, idBonificacion, idMonto, idCompania, null);
        }
        
        /// <remarks/>
        public void setRecargaAsync(string numero, int idPersona, int idBonificacion, int idMonto, int idCompania, object userState) {
            if ((this.setRecargaOperationCompleted == null)) {
                this.setRecargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRecargaOperationCompleted);
            }
            this.InvokeAsync("setRecarga", new object[] {
                        numero,
                        idPersona,
                        idBonificacion,
                        idMonto,
                        idCompania}, this.setRecargaOperationCompleted, userState);
        }
        
        private void OnsetRecargaOperationCompleted(object arg) {
            if ((this.setRecargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRecargaCompleted(this, new setRecargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateBonificacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateBonificacion(int idBonificacion, double bonificacion, int idMonto, int idCompania) {
            object[] results = this.Invoke("updateBonificacion", new object[] {
                        idBonificacion,
                        bonificacion,
                        idMonto,
                        idCompania});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateBonificacionAsync(int idBonificacion, double bonificacion, int idMonto, int idCompania) {
            this.updateBonificacionAsync(idBonificacion, bonificacion, idMonto, idCompania, null);
        }
        
        /// <remarks/>
        public void updateBonificacionAsync(int idBonificacion, double bonificacion, int idMonto, int idCompania, object userState) {
            if ((this.updateBonificacionOperationCompleted == null)) {
                this.updateBonificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateBonificacionOperationCompleted);
            }
            this.InvokeAsync("updateBonificacion", new object[] {
                        idBonificacion,
                        bonificacion,
                        idMonto,
                        idCompania}, this.updateBonificacionOperationCompleted, userState);
        }
        
        private void OnupdateBonificacionOperationCompleted(object arg) {
            if ((this.updateBonificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateBonificacionCompleted(this, new updateBonificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateColaborador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateColaborador(int idPersona, string nombre, string apepat, string apemat, string usuario, string clave, string saldo) {
            object[] results = this.Invoke("updateColaborador", new object[] {
                        idPersona,
                        nombre,
                        apepat,
                        apemat,
                        usuario,
                        clave,
                        saldo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateColaboradorAsync(int idPersona, string nombre, string apepat, string apemat, string usuario, string clave, string saldo) {
            this.updateColaboradorAsync(idPersona, nombre, apepat, apemat, usuario, clave, saldo, null);
        }
        
        /// <remarks/>
        public void updateColaboradorAsync(int idPersona, string nombre, string apepat, string apemat, string usuario, string clave, string saldo, object userState) {
            if ((this.updateColaboradorOperationCompleted == null)) {
                this.updateColaboradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateColaboradorOperationCompleted);
            }
            this.InvokeAsync("updateColaborador", new object[] {
                        idPersona,
                        nombre,
                        apepat,
                        apemat,
                        usuario,
                        clave,
                        saldo}, this.updateColaboradorOperationCompleted, userState);
        }
        
        private void OnupdateColaboradorOperationCompleted(object arg) {
            if ((this.updateColaboradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateColaboradorCompleted(this, new updateColaboradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteColaborador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteColaborador(int idPersona) {
            object[] results = this.Invoke("deleteColaborador", new object[] {
                        idPersona});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteColaboradorAsync(int idPersona) {
            this.deleteColaboradorAsync(idPersona, null);
        }
        
        /// <remarks/>
        public void deleteColaboradorAsync(int idPersona, object userState) {
            if ((this.deleteColaboradorOperationCompleted == null)) {
                this.deleteColaboradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteColaboradorOperationCompleted);
            }
            this.InvokeAsync("deleteColaborador", new object[] {
                        idPersona}, this.deleteColaboradorOperationCompleted, userState);
        }
        
        private void OndeleteColaboradorOperationCompleted(object arg) {
            if ((this.deleteColaboradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteColaboradorCompleted(this, new deleteColaboradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBonificacionesCompletedEventHandler(object sender, getBonificacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBonificacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBonificacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBonificacionCompletedEventHandler(object sender, getBonificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBonificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBonificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getColaboradoresCompletedEventHandler(object sender, getColaboradoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getColaboradoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getColaboradoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getCompaniasCompletedEventHandler(object sender, getCompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getMontosCompletedEventHandler(object sender, getMontosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMontosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMontosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getRecargasCompletedEventHandler(object sender, getRecargasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRecargasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRecargasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getColaboradorCompletedEventHandler(object sender, getColaboradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getColaboradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getColaboradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setBonificacionCompletedEventHandler(object sender, setBonificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setBonificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setBonificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setColaboradorCompletedEventHandler(object sender, setColaboradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setColaboradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setColaboradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setCompaniaCompletedEventHandler(object sender, setCompaniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setCompaniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setCompaniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setMontoCompletedEventHandler(object sender, setMontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setMontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setMontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setRecargaCompletedEventHandler(object sender, setRecargaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setRecargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setRecargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void updateBonificacionCompletedEventHandler(object sender, updateBonificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateBonificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateBonificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void updateColaboradorCompletedEventHandler(object sender, updateColaboradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateColaboradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateColaboradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void deleteColaboradorCompletedEventHandler(object sender, deleteColaboradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteColaboradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteColaboradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591